---
# This file stores secret information like connection details. This prevents the
# accidentally sharing your credentials when sharing the more generic config.

# The connection dictionary stores all arguments passed to
# `shotgun_api3.shotgun.Shotgun` to create a SG connection.
# https://developers.shotgridsoftware.com/python-api/reference.html#shotgun

# Required
base_url: <replace>
# Use UTC timezones
convert_datetimes_to_utc: false

## Login details. Only one of these sections should be used. Replace null only
# for the section you need to use. You can remove the other section.
# A. If using a Script user
script_name: null
api_key: null

# B. If using personal user login
login: null
password: null
