---
# To prevent accidentally leaking connection details, the connection details
# are stored in a separate yaml file. Relative file paths are based in the
# same directory as the current file.
connection_file: config_example_secret.yaml

# These settings are used to filter unused information from the schema
# selected data output
ignored:
  # Don't include any fields on any entities with this data type
  data_types:
    - pivot_column

  # Don't show these entities when listing available entities. These are
  # respected when using the all and missing entity_types in the cli.
  # `Attachments` normally don't need archived as the file down-loader takes
  # care of downloading them.
  # `EventLogEntry` likely won't make sense to archive as its a very verbose
  # record of all changes made to most other tables over the last 6 months.
  entity_types:
    - Attachment
    - EventLogEntry
    - Page
    - PageHit
    - PageSetting
    - PermissionRuleSet
    - RvLicense
    - TimeLog
    - WorkDayRule
    - Version_sg_uses_versions_Connection

  # Don't show these fields when selecting a specific entity
  fields:
    Attachment:
      - image_source_entity
    Project:
      - landing_page_url
    Version:
      - viewed_by_current_user
      - viewed_by_current_user_at

  # When processing attachments if these file extensions are encountered
  # record them but don't actually download the files. This is useful for
  # preventing downloading the source `sg_uploaded_movie` .mov file when
  # the re-encoded .mp4 `sg_uploaded_movie_mp4` will suffice. It will however
  # still download other file formats.
  file_exts:
    Version:
      sg_uploaded_movie:
        - .mov

html:
  exclude_details:
    # Exclude these fields if encountered on any entity_type
    global:
      - cached_display_name
    # Other keys are entity_types and only exclude fields for that type
    Note:
      - replies
      - reply_content
      - sg_downstream_dependency_estimate
    Project:
      - filmstrip_image
      - image
      - image_blur_hash
      - image_source_entity
    Version:
      - filmstrip_image
      - image
      - image_blur_hash
      - sg_uploaded_movie
      - sg_uploaded_movie_image
      - sg_uploaded_movie_mp4
      - sg_uploaded_movie_transcoding_status
      - sg_uploaded_movie_webm

  list_fields:
    # Only show these fields in list_entities view for each entity_type.
    # The field order is respected in the list view.
    Project:
      # - name
      - sg_status
      - archived
      - id
      - created_at
      - created_by
      - updated_at
      - updated_by
      - layout_project
    Asset:
      - code
      - sg_status_list
      - sg_asset_type
      - description
      - addressings_cc
      - updated_at
      - updated_by
      - created_at
      - created_by
      - tags
      - id
      - linked_projects
      - open_notes_count
      - project
    Note:
      - sg_status_list
      - subject
      - user
      - id
      - created_at
      - sg_note_type
      - project
    Task:
      - sg_status_list
      - id
      - tags
      - sg_description
      - project
      - open_notes_count
    Version:
      - code
      - sg_status_list
      - id
      - sg_version_type

  sort_field:
    # Sort entities in the list view. The value is passed as order to the
    # shotgun_api3 `find` method.
    Asset:
      - field_name: code
        direction: asc
    Note:
      - field_name: subject
        direction: asc
      - field_name: content
        direction: asc
    Version:
      - field_name: code
        direction: asc

# Filters can be used to define shotgun_api3 filters for each entity.
# https://developers.shotgridsoftware.com/python-api/reference.html#shotgun_api3.shotgun.Shotgun.find
# These are stored per entity_type

# filters:
#   Version:
#     [
#       # ['id', 'in', [105, 127, 190, 434]]
#     ]
